// Dans lib/models/account.dart
class Account {
  final String id;
  final String number;
  final String name;
  final String type;
  final String? accountNumber;
  final String? currency;
  final String? plan; // Dans le constructeur

  Account({
    required this.id,
    required this.number,
    required this.name,
    required this.type,
    this.accountNumber,
    this.currency,
        this.plan,
  });

// N'oubliez pas de mettre à jour factory Account.fromJson et toJson si nécessaire


  factory Account.fromJson(Map<String, dynamic> json) {
    // On récupère le numéro de compte
    String num = json['number']?.toString() ?? '';


    return Account(
      id: json['id']?.toString() ?? '',
      number: num,
      name: json['name'] ?? '',
      type: json['type'] ?? '',
      // Si accountNumber est vide dans le JSON, on utilise 'number' ou 'code'
      accountNumber: json['accountNumber']?.toString() ??
          (json['code']?.toString() ?? num),
      currency: json['currency']?.toString(), // <--- AJOUTEZ CETTE LIGNE
    );
  }

  Map<String, dynamic> toJson() =>
      {
        'id': id,
        'number': number,
        'accountNumber': accountNumber ?? number,
        // Sécurité : on met le number si null
        'name': name,
        'type': type,
      };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
          other is Account &&
              runtimeType == other.runtimeType &&
              id == other.id &&
              number == other.number;

  @override
  int get hashCode => id.hashCode ^ number.hashCode;

  @override
  String toString() => '$number - $name';

  // Liste par défaut : Vigilance maintenue sur tous les types de comptes
  static List<Account> get defaultAccounts =>
      [
        Account(id: '101', number: '101', name: 'Capital', type: 'capitaux'),
        Account(id: '1011', number: '1011', name: 'Capital souscrit - non appelé', type: 'capitaux'),
        Account(id: '1012', number: '1012', name: 'Capital souscrit - appelé, non versé', type: 'capitaux'),
        Account(id: '1013', number: '1013', name: 'Capital souscrit - appelé, versé', type: 'capitaux'),
        Account(id: '10131', number: '10131', name: 'Capital non amorti', type: 'capitaux'),
        Account(id: '10132', number: '10132', name: 'Capital amorti', type: 'capitaux'),
        Account(id: '1018', number: '1018', name: 'Capital souscrit soumis à des réglementations particulières', type: 'capitaux'),
        Account(id: '102', number: '102', name: 'Fonds fiduciaires', type: 'capitaux'),
        Account(id: '104', number: '104', name: 'Primes liées au capital', type: 'capitaux'),
        Account(id: '1041', number: '1041', name: 'Primes d\'émission', type: 'capitaux'),
        Account(id: '1042', number: '1042', name: 'Primes de fusion', type: 'capitaux'),
        Account(id: '1043', number: '1043', name: 'Primes d\'apport', type: 'capitaux'),
        Account(id: '1044', number: '1044', name: 'Primes de conversion d\'obligations en actions', type: 'capitaux'),
        Account(id: '1045', number: '1045', name: 'Bons de souscription d\'actions', type: 'capitaux'),
        Account(id: '105', number: '105', name: 'Écarts de réévaluation', type: 'capitaux'),
        Account(id: '106', number: '106', name: 'Réserves', type: 'capitaux'),
        Account(id: '1061', number: '1061', name: 'Réserve légale', type: 'capitaux'),
        Account(id: '1062', number: '1062', name: 'Réserves indisponibles', type: 'capitaux'),
        Account(id: '1063', number: '1063', name: 'Réserves statutaires ou contractuelles', type: 'capitaux'),
        Account(id: '1064', number: '1064', name: 'Réserves réglementées', type: 'capitaux'),
        Account(id: '1068', number: '1068', name: 'Autres réserves', type: 'capitaux'),
        Account(id: '107', number: '107', name: 'Écart d\'équivalence', type: 'capitaux'),
        Account(id: '108', number: '108', name: 'Compte de l\'exploitant', type: 'capitaux'),
        Account(id: '109', number: '109', name: 'Actionnaires : capital souscrit - non appelé', type: 'capitaux'),

        Account(id: '11', number: '11', name: 'Report à nouveau', type: 'capitaux'),
        Account(id: '110', number: '110', name: 'Report à nouveau - solde créditeur', type: 'capitaux'),
        Account(id: '119', number: '119', name: 'Report à nouveau - solde débiteur', type: 'capitaux'),

        Account(id: '12', number: '12', name: 'Résultat de l\'exercice', type: 'capitaux'),
        Account(id: '120', number: '120', name: 'Résultat de l\'exercice - bénéfice', type: 'capitaux'),
        Account(id: '1209', number: '1209', name: 'Acomptes sur dividendes', type: 'capitaux'),
        Account(id: '129', number: '129', name: 'Résultat de l\'exercice - perte', type: 'capitaux'),

        Account(id: '13', number: '13', name: 'Subventions d\'investissement', type: 'capitaux'),
        Account(id: '131', number: '131', name: 'Subventions d\'investissement octroyées', type: 'capitaux'),
        Account(id: '139', number: '139', name: 'Subventions d\'investissement inscrites au compte de résultat', type: 'capitaux'),

        Account(id: '14', number: '14', name: 'Provisions réglementées', type: 'capitaux'),
        Account(id: '143', number: '143', name: 'Provisions réglementées pour hausse de prix', type: 'capitaux'),
        Account(id: '145', number: '145', name: 'Amortissements dérogatoires', type: 'capitaux'),
        Account(id: '148', number: '148', name: 'Autres provisions réglementées', type: 'capitaux'),

        Account(id: '15', number: '15', name: 'Provisions', type: 'capitaux'),
        Account(id: '151', number: '151', name: 'Provisions pour risques', type: 'capitaux'),
        Account(id: '1511', number: '1511', name: 'Provisions pour litiges', type: 'capitaux'),
        Account(id: '1512', number: '1512', name: 'Provisions pour garanties données aux clients', type: 'capitaux'),
        Account(id: '1514', number: '1514', name: 'Provisions pour amendes et pénalités', type: 'capitaux'),
        Account(id: '1515', number: '1515', name: 'Provisions pour pertes de change', type: 'capitaux'),
        Account(id: '1516', number: '1516', name: 'Provisions pour pertes sur contrats', type: 'capitaux'),
        Account(id: '1518', number: '1518', name: 'Autres provisions pour risques', type: 'capitaux'),
        Account(id: '152', number: '152', name: 'Provisions pour charges', type: 'capitaux'),
        Account(id: '1521', number: '1521', name: 'Provisions pour pensions et obligations similaires', type: 'capitaux'),
        Account(id: '1522', number: '1522', name: 'Provisions pour restructurations', type: 'capitaux'),
        Account(id: '1523', number: '1523', name: 'Provisions pour impôts', type: 'capitaux'),
        Account(id: '1524', number: '1524', name: 'Provisions pour renouvellement des immobilisations', type: 'capitaux'),
        Account(id: '1525', number: '1525', name: 'Provisions pour gros entretien ou grandes révisions', type: 'capitaux'),
        Account(id: '1526', number: '1526', name: 'Provisions pour remise en état', type: 'capitaux'),
        Account(id: '1527', number: '1527', name: 'Autres provisions pour charges', type: 'capitaux'),

        Account(id: '16', number: '16', name: 'Emprunts et dettes assimilées', type: 'dette'),
        Account(id: '161', number: '161', name: 'Emprunts obligataires convertibles', type: 'dette'),
        Account(id: '1618', number: '1618', name: 'Intérêts courus sur emprunts obligataires convertibles', type: 'dette'),
        Account(id: '162', number: '162', name: 'Obligations représentatives de passifs nets remis en fiducie', type: 'dette'),
        Account(id: '163', number: '163', name: 'Autres emprunts obligataires', type: 'dette'),
        Account(id: '1638', number: '1638', name: 'Intérêts courus sur autres emprunts obligataires', type: 'dette'),
        Account(id: '164', number: '164', name: 'Emprunts auprès des établissements de crédit', type: 'dette'),
        Account(id: '1648', number: '1648', name: 'Intérêts courus sur emprunts auprès des établissements de crédit', type: 'dette'),
        Account(id: '165', number: '165', name: 'Dépôts et cautionnements reçus', type: 'dette'),

        Account(id: '1655', number: '1655', name: 'Cautionnements', type: 'dette'),
        Account(id: '1658', number: '1658', name: 'Intérêts courus sur dépôts et cautionnements reçus', type: 'dette'),
        Account(id: '166', number: '166', name: 'Participation des salariés aux résultats', type: 'dette'),
        Account(id: '1661', number: '1661', name: 'Comptes bloqués', type: 'dette'),
        Account(id: '1662', number: '1662', name: 'Fonds de participation', type: 'dette'),
        Account(id: '1668', number: '1668', name: 'Intérêts courus sur participation des salariés aux résultats', type: 'dette'),



        Account(id: '167', number: '167', name: 'Emprunts et dettes assortis de conditions particulières', type: 'dette'),
        Account(id: '168', number: '168', name: 'Autres emprunts et dettes assimilées', type: 'dette'),
        Account(id: '1681', number: '1681', name: 'Autres emprunts', type: 'dette'),
        Account(id: '1685', number: '1685', name: 'Rentes viagères capitalisées', type: 'dette'),
        Account(id: '1687', number: '1687', name: 'Autres dettes', type: 'dette'),
        Account(id: '1688', number: '1688', name: 'Intérêts courus sur emprunts et dettes visés à l\'article 168', type: 'dette'),
        Account(id: '169', number: '169', name: 'Primes d\'émission de titres à revenu fixe', type: 'dette'),

        Account(id: '17', number: '17', name: 'Dettes rattachées à des participations', type: 'dette'),
        Account(id: '171', number: '171', name: 'Dettes rattachées à des participations (groupe)', type: 'dette'),
        Account(id: '174', number: '174', name: 'Dettes rattachées à des participations (hors groupe)', type: 'dette'),
        Account(id: '178', number: '178', name: 'Intérêts courus sur dettes rattachées à des participations', type: 'dette'),

        Account(id: '18', number: '18', name: 'Comptes de liaison des établissements et sociétés en participation', type: 'capitaux'),
        Account(id: '181', number: '181', name: 'Comptes de liaison des établissements', type: 'capitaux'),
        Account(id: '186', number: '186', name: 'Biens et services mis à la disposition des sociétés en participation', type: 'capitaux'),
        Account(id: '187', number: '187', name: 'Comptes de liaison des sociétés en participation', type: 'capitaux'),

        // --- CLASSE 2 : COMPTES D'IMMOBILISATIONS ---
        Account(id: '20', number: '20', name: 'Immobilisations incorporelles', type: 'immobilisation'),
        Account(id: '201', number: '201', name: 'Frais d\'établissement', type: 'immobilisation'),
        Account(id: '2011', number: '2011', name: 'Frais de constitution', type: 'immobilisation'),
        Account(id: '2012', number: '2012', name: 'Frais de premier établissement', type: 'immobilisation'),
        Account(id: '20121', number: '20121', name: 'Frais de prospection', type: 'immobilisation'),
        Account(id: '20122', number: '20122', name: 'Frais de publicité', type: 'immobilisation'),
        Account(id: '2013', number: '2013', name: 'Frais d\'augmentation de capital et d\'opérations diverses', type: 'immobilisation'),
        Account(id: '203', number: '203', name: 'Frais de recherche et de développement', type: 'immobilisation'),
        Account(id: '205', number: '205', name: 'Concessions, brevets, licences, marques, procédés, logiciels', type: 'immobilisation'),
        Account(id: '206', number: '206', name: 'Droit au bail', type: 'immobilisation'),
        Account(id: '207', number: '207', name: 'Fonds commercial', type: 'immobilisation'),
        Account(id: '208', number: '208', name: 'Autres immobilisations incorporelles', type: 'immobilisation'),

        Account(id: '21', number: '21', name: 'Immobilisations corporelles', type: 'immobilisation'),
        Account(id: '211', number: '211', name: 'Terrains', type: 'immobilisation'),
        Account(id: '2111', number: '2111', name: 'Terrains nus', type: 'immobilisation'),
        Account(id: '2112', number: '2112', name: 'Terrains aménagés', type: 'immobilisation'),
        Account(id: '2113', number: '2113', name: 'Sous-sols et surpoids', type: 'immobilisation'),
        Account(id: '2114', number: '2114', name: 'Terrains de gisements', type: 'immobilisation'),
        Account(id: '21141', number: '21141', name: 'Carrières', type: 'immobilisation'),
        Account(id: '2115', number: '2115', name: 'Terrains bâtis', type: 'immobilisation'),
        Account(id: '2116', number: '2116', name: 'Compte d\'ordre sur terrains mis en concession', type: 'immobilisation'),
        Account(id: '212', number: '212', name: 'Cheptel', type: 'immobilisation'),


        Account(id: '2186', number: '2186', name: 'Emballages récupérables', type: 'immobilisation'),
        Account(id: '2187', number: '2187', name: 'Mali de fusion sur actifs corporels', type: 'immobilisation'),

        Account(id: '22', number: '22', name: 'Immobilisations mises en concession', type: 'immobilisation'),
        Account(id: '229', number: '229', name: 'Droits du concédant', type: 'immobilisation'),

        Account(id: '23', number: '23', name: 'Immobilisations en cours, avances et acomptes', type: 'immobilisation'),
        Account(id: '231', number: '231', name: 'Immobilisations corporelles en cours', type: 'immobilisation'),
        Account(id: '232', number: '232', name: 'Immobilisations incorporelles en cours', type: 'immobilisation'),
        Account(id: '237', number: '237', name: 'Avances et acomptes versés sur commandes d\'immobilisations incorporelles', type: 'immobilisation'),
        Account(id: '238', number: '238', name: 'Avances et acomptes versés sur commandes d\'immobilisations corporelles', type: 'immobilisation'),
        Account(id: '26', number: '26', name: 'Participations et créances rattachées à des participations', type: 'immobilisation'),
        Account(id: '261', number: '261', name: 'Titres de participation', type: 'immobilisation'),
        Account(id: '2611', number: '2611', name: 'Actions', type: 'immobilisation'),
        Account(id: '2618', number: '2618', name: 'Autres titres', type: 'immobilisation'),
        Account(id: '262', number: '262', name: 'Titres évalués par équivalence', type: 'immobilisation'),
        Account(id: '266', number: '266', name: 'Autres formes de participation', type: 'immobilisation'),
        Account(id: '2661', number: '2661', name: 'Droits représentatifs d\'actifs nets remis en fiducie', type: 'immobilisation'),
        Account(id: '267', number: '267', name: 'Créances rattachées à des participations', type: 'immobilisation'),
        Account(id: '2671', number: '2671', name: 'Créances rattachées à des participations-groupe', type: 'immobilisation'),
        Account(id: '2674', number: '2674', name: 'Créances rattachées à des participations - hors groupe', type: 'immobilisation'),
        Account(id: '2675', number: '2675', name: 'Versements représentatifs d\'apports non capitalisés - appel de fonds', type: 'immobilisation'),
        Account(id: '2676', number: '2676', name: 'Avances consolidables', type: 'immobilisation'),
        Account(id: '2677', number: '2677', name: 'Autres créances rattachées à des participations', type: 'immobilisation'),
        Account(id: '2678', number: '2678', name: 'Intérêts courus', type: 'immobilisation'),
        Account(id: '268', number: '268', name: 'Créances rattachées à des sociétés en participation', type: 'immobilisation'),
        Account(id: '2681', number: '2681', name: 'Principal', type: 'immobilisation'),
        Account(id: '2688', number: '2688', name: 'Intérêts courus', type: 'immobilisation'),
        Account(id: '269', number: '269', name: 'Versements restant à effectuer sur titres de participation non libérés', type: 'immobilisation'),

        Account(id: '27', number: '27', name: 'Autres immobilisations financières', type: 'immobilisation'),
        Account(id: '271', number: '271', name: 'Titres immobilisés autres que les titres immobilisés de l\'activité de portefeuille (droit de propriété)', type: 'immobilisation'),
        Account(id: '2711', number: '2711', name: 'Actions', type: 'immobilisation'),
        Account(id: '2718', number: '2718', name: 'Autres titres', type: 'immobilisation'),
        Account(id: '272', number: '272', name: 'Titres immobilisés (droit de créance)', type: 'immobilisation'),
        Account(id: '2721', number: '2721', name: 'Obligations', type: 'immobilisation'),
        Account(id: '2722', number: '2722', name: 'Bons', type: 'immobilisation'),
        Account(id: '273', number: '273', name: 'Titres immobilisés de l\'activité de portefeuille', type: 'immobilisation'),
        Account(id: '274', number: '274', name: 'Prêts', type: 'immobilisation'),
        Account(id: '2741', number: '2741', name: 'Prêts participatifs', type: 'immobilisation'),
        Account(id: '2742', number: '2742', name: 'Prêts aux associés', type: 'immobilisation'),
        Account(id: '2743', number: '2743', name: 'Prêts au personnel', type: 'immobilisation'),
        Account(id: '2748', number: '2748', name: 'Autres prêts', type: 'immobilisation'),
        Account(id: '275', number: '275', name: 'Dépôts et cautionnements versés', type: 'immobilisation'),
        Account(id: '2751', number: '2751', name: 'Dépôts', type: 'immobilisation'),
        Account(id: '2755', number: '2755', name: 'Cautionnements', type: 'immobilisation'),
        Account(id: '276', number: '276', name: 'Autres créances immobilisées', type: 'immobilisation'),
        Account(id: '2761', number: '2761', name: 'Créances diverses', type: 'immobilisation'),
        Account(id: '2768', number: '2768', name: 'Intérêts courus', type: 'immobilisation'),
        Account(id: '27682', number: '27682', name: 'Intérêts courus sur titres immobilisés (droit de créance)', type: 'immobilisation'),
        Account(id: '27684', number: '27684', name: 'Intérêts courus sur prêts', type: 'immobilisation'),
        Account(id: '27685', number: '27685', name: 'Intérêts courus sur dépôts et cautionnements', type: 'immobilisation'),
        Account(id: '27688', number: '27688', name: 'Intérêts courus sur créances diverses', type: 'immobilisation'),
        Account(id: '277', number: '277', name: 'Actions propres ou parts propres', type: 'immobilisation'),
        Account(id: '2771', number: '2771', name: 'Actions propres ou parts propres', type: 'immobilisation'),
        Account(id: '2772', number: '2772', name: 'Actions propres ou parts propres en voie d\'annulation', type: 'immobilisation'),
        Account(id: '278', number: '278', name: 'Mali de fusion sur actifs financiers', type: 'immobilisation'),
        Account(id: '279', number: '279', name: 'Versements restant à effectuer sur titres immobilisés non libérés', type: 'immobilisation'),

        Account(id: '28', number: '28', name: 'Amortissements des immobilisations', type: 'immobilisation'),
        Account(id: '280', number: '280', name: 'Amortissements des immobilisations incorporelles et des frais d\'établissement', type: 'immobilisation'),
        Account(id: '2801', number: '2801', name: 'Frais d\'établissement', type: 'immobilisation'),
        Account(id: '2803', number: '2803', name: 'Frais de développement', type: 'immobilisation'),
        Account(id: '2805', number: '2805', name: 'Concessions et droits similaires, brevets, licences, solutions informatiques, droits et valeurs similaires', type: 'immobilisation'),
        Account(id: '2806', number: '2806', name: 'Droit au bail', type: 'immobilisation'),
        Account(id: '2807', number: '2807', name: 'Fonds commercial', type: 'immobilisation'),
        Account(id: '2808', number: '2808', name: 'Autres immobilisations incorporelles', type: 'immobilisation'),
        Account(id: '281', number: '281', name: 'Amortissements des immobilisations corporelles', type: 'immobilisation'),
        Account(id: '2812', number: '2812', name: 'Agencements, aménagements de terrains', type: 'immobilisation'),
        Account(id: '2813', number: '2813', name: 'Constructions', type: 'immobilisation'),
        Account(id: '2814', number: '2814', name: 'Constructions sur sol d\'autrui', type: 'immobilisation'),
        Account(id: '2815', number: '2815', name: 'Installations, matériel et outillage industriels', type: 'immobilisation'),
        Account(id: '2818', number: '2818', name: 'Autres immobilisations corporelles', type: 'immobilisation'),
        Account(id: '28187', number: '28187', name: 'Amortissement du mali de fusion sur actifs corporels', type: 'immobilisation'),
        Account(id: '282', number: '282', name: 'Amortissements des immobilisations mises en concession', type: 'immobilisation'),

        Account(id: '29', number: '29', name: 'Dépréciations des immobilisations', type: 'immobilisation'),
        Account(id: '290', number: '290', name: 'Dépréciations des immobilisations incorporelles', type: 'immobilisation'),
        Account(id: '2901', number: '2901', name: 'Frais d\'établissement', type: 'immobilisation'),
        Account(id: '2903', number: '2903', name: 'Frais de développement', type: 'immobilisation'),
        Account(id: '2905', number: '2905', name: 'Marques, procédés, droits et valeurs similaires', type: 'immobilisation'),
        Account(id: '2906', number: '2906', name: 'Droit au bail', type: 'immobilisation'),
        Account(id: '2907', number: '2907', name: 'Fonds commercial', type: 'immobilisation'),
        Account(id: '2908', number: '2908', name: 'Autres immobilisations incorporelles', type: 'immobilisation'),
        Account(id: '29081', number: '29081', name: 'Dépréciation du mali de fusion sur actifs incorporels', type: 'immobilisation'),

        Account(id: '291', number: '291', name: 'Dépréciations des immobilisations corporelles', type: 'immobilisation'),
        Account(id: '2911', number: '2911', name: 'Terrains', type: 'immobilisation'),
        Account(id: '2912', number: '2912', name: 'Agencements et aménagements de terrains', type: 'immobilisation'),
        Account(id: '2913', number: '2913', name: 'Constructions', type: 'immobilisation'),
        Account(id: '2914', number: '2914', name: 'Constructions sur sol d\'autrui', type: 'immobilisation'),
        Account(id: '2915', number: '2915', name: 'Installations techniques, matériels et outillages industriels', type: 'immobilisation'),
        Account(id: '2918', number: '2918', name: 'Autres immobilisations corporelles', type: 'immobilisation'),
        Account(id: '29187', number: '29187', name: 'Dépréciation du mali de fusion sur actifs corporels', type: 'immobilisation'),

        Account(id: '292', number: '292', name: 'Dépréciations des immobilisations mises en concession', type: 'immobilisation'),

        Account(id: '293', number: '293', name: 'Dépréciations des immobilisations en cours', type: 'immobilisation'),
        Account(id: '2931', number: '2931', name: 'Immobilisations corporelles en cours', type: 'immobilisation'),
        Account(id: '2932', number: '2932', name: 'Immobilisations incorporelles en cours', type: 'immobilisation'),

        Account(id: '296', number: '296', name: 'Dépréciations des participations et créances rattachées à des participations', type: 'immobilisation'),
        Account(id: '2961', number: '2961', name: 'Titres de participation', type: 'immobilisation'),
        Account(id: '2962', number: '2962', name: 'Titres évalués par équivalence', type: 'immobilisation'),
        Account(id: '2966', number: '2966', name: 'Autres formes de participation', type: 'immobilisation'),
        Account(id: '2967', number: '2967', name: 'Créances rattachées à des participations', type: 'immobilisation'),
        Account(id: '2968', number: '2968', name: 'Créances rattachées à des sociétés en participation', type: 'immobilisation'),

        Account(id: '297', number: '297', name: 'Dépréciations des autres immobilisations financières', type: 'immobilisation'),
        Account(id: '2971', number: '2971', name: 'Titres immobilisés autres que les titres immobilisés de l\'activité de portefeuille (droit de propriété)', type: 'immobilisation'),
        Account(id: '2972', number: '2972', name: 'Titres immobilisés (droit de créance)', type: 'immobilisation'),
        Account(id: '2973', number: '2973', name: 'Titres immobilisés de l\'activité de portefeuille', type: 'immobilisation'),
        Account(id: '2974', number: '2974', name: 'Prêts', type: 'immobilisation'),
        Account(id: '2975', number: '2975', name: 'Dépôts et cautionnements versés', type: 'immobilisation'),
        Account(id: '2976', number: '2976', name: 'Autres créances immobilisées', type: 'immobilisation'),

        // --- CLASSE 3 : COMPTES DE STOCKS ET EN-COURS ---
        Account(id: '31', number: '31', name: 'Matières premières et fournitures', type: 'stock'),

        Account(id: '32', number: '32', name: 'Autres approvisionnements', type: 'stock'),
        Account(id: '321', number: '321', name: 'Matières consommables', type: 'stock'),
        Account(id: '322', number: '322', name: 'Fournitures consommables', type: 'stock'),
        Account(id: '3221', number: '3221', name: 'Combustibles', type: 'stock'),
        Account(id: '3222', number: '3222', name: 'Produits d\'entretien', type: 'stock'),
        Account(id: '3223', number: '3223', name: 'Fournitures d\'atelier et d\'usine', type: 'stock'),
        Account(id: '3224', number: '3224', name: 'Fournitures de magasin', type: 'stock'),
        Account(id: '3225', number: '3225', name: 'Fournitures de bureau', type: 'stock'),
        Account(id: '326', number: '326', name: 'Emballages', type: 'stock'),
        Account(id: '3261', number: '3261', name: 'Emballages perdus', type: 'stock'),
        Account(id: '3265', number: '3265', name: 'Emballages récupérables non identifiables', type: 'stock'),
        Account(id: '3267', number: '3267', name: 'Emballages à usage mixte', type: 'stock'),

        Account(id: '33', number: '33', name: 'En-cours de production de biens', type: 'stock'),
        Account(id: '331', number: '331', name: 'Produits en cours', type: 'stock'),
        Account(id: '335', number: '335', name: 'Travaux en cours', type: 'stock'),

        Account(id: '34', number: '34', name: 'En-cours de production de services', type: 'stock'),
        Account(id: '341', number: '341', name: 'Etudes en cours', type: 'stock'),
        Account(id: '345', number: '345', name: 'Prestations de services en cours', type: 'stock'),

        Account(id: '35', number: '35', name: 'Stocks de produits', type: 'stock'),
        Account(id: '351', number: '351', name: 'Produits intermédiaires', type: 'stock'),
        Account(id: '355', number: '355', name: 'Produits finis', type: 'stock'),
        Account(id: '358', number: '358', name: 'Produits résiduels ou matières de récupération', type: 'stock'),
        Account(id: '3581', number: '3581', name: 'Déchets', type: 'stock'),
        Account(id: '3585', number: '3585', name: 'Rebuts', type: 'stock'),
        Account(id: '3586', number: '3586', name: 'Matières de récupération', type: 'stock'),

        Account(id: '37', number: '37', name: 'Stocks de marchandises', type: 'stock'),

        Account(id: '39', number: '39', name: 'Dépréciations des stocks et en-cours', type: 'stock'),
        Account(id: '391', number: '391', name: 'Dépréciations des matières premières et fournitures', type: 'stock'),
        Account(id: '392', number: '392', name: 'Dépréciations des autres approvisionnements', type: 'stock'),
        Account(id: '393', number: '393', name: 'Dépréciations des en-cours de production de biens', type: 'stock'),
        Account(id: '394', number: '394', name: 'Dépréciations des en-cours de production de services', type: 'stock'),
        Account(id: '395', number: '395', name: 'Dépréciations des stocks de produits', type: 'stock'),
        Account(id: '397', number: '397', name: 'Dépréciations des stocks de marchandises', type: 'stock'),
        Account(id: '401', number: '401', name: 'Fournisseurs', type: 'tiers'),
        Account(id: '4011', number: '4011', name: 'Fournisseurs - Achats de biens et prestations de services', type: 'tiers'),
        Account(id: '4017', number: '4017', name: 'Fournisseurs - Retenues de garantie', type: 'tiers'),

        Account(id: '403', number: '403', name: 'Fournisseurs - Effets à payer', type: 'tiers'),

        Account(id: '404', number: '404', name: 'Fournisseurs d\'immobilisations', type: 'tiers'),
        Account(id: '4041', number: '4041', name: 'Fournisseurs - Achats d\'immobilisations', type: 'tiers'),
        Account(id: '4047', number: '4047', name: 'Fournisseurs d\'immobilisations - Retenues de garantie', type: 'tiers'),

        Account(id: '405', number: '405', name: 'Fournisseurs d\'immobilisations - Effets à payer', type: 'tiers'),

        Account(id: '408', number: '408', name: 'Fournisseurs - Factures non parvenues', type: 'tiers'),
        Account(id: '4081', number: '4081', name: 'Fournisseurs', type: 'tiers'),
        Account(id: '4084', number: '4084', name: 'Fournisseurs d\'immobilisations', type: 'tiers'),
        Account(id: '4088', number: '4088', name: 'Fournisseurs - Intérêts courus', type: 'tiers'),

        Account(id: '409', number: '409', name: 'Fournisseurs débiteurs', type: 'tiers'),
        Account(id: '4091', number: '4091', name: 'Fournisseurs - Avances et acomptes versés sur commandes', type: 'tiers'),
        Account(id: '4096', number: '4096', name: 'Fournisseurs - Créances pour emballages et matériel à rendre', type: 'tiers'),
        Account(id: '4097', number: '4097', name: 'Fournisseurs - Autres avoirs', type: 'tiers'),
        Account(id: '40971', number: '40971', name: 'Fournisseurs d\'exploitation', type: 'tiers'),
        Account(id: '40974', number: '40974', name: 'Fournisseurs d\'immobilisations', type: 'tiers'),
        Account(id: '4098', number: '4098', name: 'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus', type: 'tiers'),

        Account(id: '41', number: '41', name: 'Clients et comptes rattachés', type: 'tiers'),
        Account(id: '411', number: '411', name: 'Clients', type: 'tiers'),
        Account(id: '4111', number: '4111', name: 'Clients-Ventes de biens ou de prestations de services', type: 'tiers'),
        Account(id: '4117', number: '4117', name: 'Clients-Retenues de garantie', type: 'tiers'),
        Account(id: '413', number: '413', name: 'Clients - Effets à recevoir', type: 'tiers'),
        Account(id: '416', number: '416', name: 'Clients douteux ou litigieux', type: 'tiers'),
        Account(id: '418', number: '418', name: 'Clients-Produits non encore facturés', type: 'tiers'),
        Account(id: '4181', number: '4181', name: 'Clients - Factures à établir', type: 'tiers'),
        Account(id: '4188', number: '4188', name: 'Clients - Intérêts courus', type: 'tiers'),
        Account(id: '419', number: '419', name: 'Clients créditeurs', type: 'tiers'),
        Account(id: '4191', number: '4191', name: 'Clients-Avances et acomptes reçus sur commandes', type: 'tiers'),
        Account(id: '4196', number: '4196', name: 'Clients-Dettes sur emballages et matériels consignés', type: 'tiers'),
        Account(id: '4197', number: '4197', name: 'Clients - Autres avoirs', type: 'tiers'),
        Account(id: '4198', number: '4198', name: 'Rabais, remises, ristournes à accorder et autres avoirs à établir', type: 'tiers'),

        Account(id: '42', number: '42', name: 'Personnel et comptes rattachés', type: 'tiers'),
        Account(id: '421', number: '421', name: 'Personnel - Rémunérations dues', type: 'tiers'),
        Account(id: '422', number: '422', name: 'Comité social et économique', type: 'tiers'),
        Account(id: '424', number: '424', name: 'Participation des salariés aux résultats', type: 'tiers'),
        Account(id: '4246', number: '4246', name: 'Réserve spéciale', type: 'tiers'),
        Account(id: '4248', number: '4248', name: 'Comptes courants', type: 'tiers'),
        Account(id: '425', number: '425', name: 'Personnel-Avances et acomptes et autres comptes débiteurs', type: 'tiers'),
        Account(id: '426', number: '426', name: 'Personnel - Dépôts', type: 'tiers'),
        Account(id: '427', number: '427', name: 'Personnel- Oppositions', type: 'tiers'),
        Account(id: '428', number: '428', name: 'Personnel-Charges à payer', type: 'tiers'),
        Account(id: '4282', number: '4282', name: 'Dettes provisionnées pour congés à payer', type: 'tiers'),
        Account(id: '4284', number: '4284', name: 'Dettes provisionnées pour participation des salariés aux résultats', type: 'tiers'),
        Account(id: '4286', number: '4286', name: 'Autres charges à payer', type: 'tiers'),

        Account(id: '43', number: '43', name: 'Sécurité sociale et autres organismes sociaux', type: 'tiers'),
        Account(id: '431', number: '431', name: 'Sécurité sociale', type: 'tiers'),
        Account(id: '437', number: '437', name: 'Autres organismes sociaux', type: 'tiers'),
        Account(id: '438', number: '438', name: 'Organismes sociaux-Charges à payer', type: 'tiers'),
        Account(id: '4382', number: '4382', name: 'Charges sociales sur congés à payer', type: 'tiers'),
        Account(id: '4386', number: '4386', name: 'Autres charges à payer', type: 'tiers'),
        Account(id: '439', number: '439', name: 'Organismes sociaux - Produits à recevoir', type: 'tiers'),

        Account(id: '44', number: '44', name: 'État et autres collectivités publiques', type: 'tiers'),
        Account(id: '441', number: '441', name: 'Etat-Subventions et aides à recevoir', type: 'tiers'),
        Account(id: '442', number: '442', name: 'Contributions, impôts et taxes recouvrés pour le compte de l\'État', type: 'tiers'),
        Account(id: '4421', number: '4421', name: 'Prélèvements à la source (Impôt sur le revenu)', type: 'tiers'),
        Account(id: '4422', number: '4422', name: 'Prélèvements forfaitaires non libératoires', type: 'tiers'),
        Account(id: '4423', number: '4423', name: 'Retenues et prélèvements sur les distributions', type: 'tiers'),
        Account(id: '444', number: '444', name: 'État-Impôts sur les bénéfices', type: 'tiers'),
        Account(id: '445', number: '445', name: 'État-Taxes sur le chiffre d\'affaires', type: 'tiers'),
        Account(id: '4452', number: '4452', name: 'TVA due intracommunautaire', type: 'tiers'),
        Account(id: '4455', number: '4455', name: 'Taxes sur le chiffre d\'affaires à décaisser', type: 'tiers'),
        Account(id: '44551', number: '44551', name: 'TVA à décaisser', type: 'tiers'),
        Account(id: '44558', number: '44558', name: 'Taxes assimilées à la TVA', type: 'tiers'),
        Account(id: '4456', number: '4456', name: 'Taxes sur le chiffre d\'affaires déductibles', type: 'tiers'),
        Account(id: '44562', number: '44562', name: 'TVA sur immobilisations', type: 'tiers'),
        Account(id: '44563', number: '44563', name: 'TVA transférée par d\'autres entités', type: 'tiers'),
        Account(id: '44566', number: '44566', name: 'TVA sur autres biens et services', type: 'tiers'),
        Account(id: '44567', number: '44567', name: 'Crédit de TVA à reporter', type: 'tiers'),
        Account(id: '44568', number: '44568', name: 'Taxes assimilées à la TVA', type: 'tiers'),
        Account(id: '4457', number: '4457', name: 'Taxes sur le chiffre d\'affaires collectées', type: 'tiers'),
        Account(id: '44571', number: '44571', name: 'TVA collectée', type: 'tiers'),
        Account(id: '44578', number: '44578', name: 'Taxes assimilées à la TVA', type: 'tiers'),
        Account(id: '4458', number: '4458', name: 'Taxes sur le chiffre d\'affaires à régulariser ou en attente', type: 'tiers'),
        Account(id: '44581', number: '44581', name: 'Acomptes - Régime simplifié d\'imposition', type: 'tiers'),
        Account(id: '44583', number: '44583', name: 'Remboursement de taxes sur le chiffre d\'affaires demandé', type: 'tiers'),
        Account(id: '44584', number: '44584', name: 'TVA récupérée d\'avance', type: 'tiers'),
        Account(id: '44586', number: '44586', name: 'Taxes sur le chiffre d\'affaires sur factures non parvenues', type: 'tiers'),
        Account(id: '44587', number: '44587', name: 'Taxes sur le chiffre d\'affaires sur factures à établir', type: 'tiers'),

        Account(id: '446', number: '446', name: 'Obligations cautionnées', type: 'tiers'),
        Account(id: '447', number: '447', name: 'Autres impôts, taxes et versements assimilés', type: 'tiers'),
        Account(id: '448', number: '448', name: 'Etat - Charges à payer et produits à recevoir', type: 'tiers'),
        Account(id: '4481', number: '4481', name: 'Etat - Charges à payer', type: 'tiers'),
        Account(id: '44811', number: '44811', name: 'Charges fiscales sur congés à payer', type: 'tiers'),
        Account(id: '44812', number: '44812', name: 'Charges à payer', type: 'tiers'),
        Account(id: '4482', number: '4482', name: 'Etat - Produits à recevoir', type: 'tiers'),

        Account(id: '449', number: '449', name: 'Quotas d\'émission à acquérir', type: 'tiers'),

        Account(id: '45', number: '45', name: 'Groupe et associés', type: 'tiers'),
        Account(id: '451', number: '451', name: 'Groupe', type: 'tiers'),
        Account(id: '455', number: '455', name: 'Associés - Comptes courants', type: 'tiers'),
        Account(id: '4551', number: '4551', name: 'Principal', type: 'tiers'),
        Account(id: '4558', number: '4558', name: 'Intérêts courus', type: 'tiers'),
        Account(id: '456', number: '456', name: 'Associés - Opérations sur le capital', type: 'tiers'),
        Account(id: '4561', number: '4561', name: 'Associés - Comptes d\'apport en société', type: 'tiers'),
        Account(id: '45611', number: '45611', name: 'Apports en nature', type: 'tiers'),
        Account(id: '45615', number: '45615', name: 'Apports en numéraire', type: 'tiers'),
        Account(id: '4562', number: '4562', name: 'Apporteurs - Capital appelé, non versé', type: 'tiers'),
        Account(id: '45621', number: '45621', name: 'Actionnaires - Capital souscrit et appelé, non versé', type: 'tiers'),
        Account(id: '45625', number: '45625', name: 'Associés - Capital appelé, non versé', type: 'tiers'),
        Account(id: '4563', number: '4563', name: 'Associés - Versements reçus sur augmentation de capital', type: 'tiers'),
        Account(id: '4564', number: '4564', name: 'Associés - Versements anticipés', type: 'tiers'),
        Account(id: '4566', number: '4566', name: 'Actionnaires défaillants', type: 'tiers'),
        Account(id: '4567', number: '4567', name: 'Associés - Capital à rembourser', type: 'tiers'),
        Account(id: '457', number: '457', name: 'Associés - Dividendes à payer', type: 'tiers'),
        Account(id: '458', number: '458', name: 'Associés - Opérations faites en commun et en GIE', type: 'tiers'),
        Account(id: '4581', number: '4581', name: 'Opérations courantes', type: 'tiers'),
        Account(id: '4588', number: '4588', name: 'Intérêts courus', type: 'tiers'),

        Account(id: '46', number: '46', name: 'Débiteurs divers et créditeurs divers', type: 'tiers'),
        Account(id: '462', number: '462', name: 'Créances sur cessions d\'immobilisations', type: 'tiers'),
        Account(id: '464', number: '464', name: 'Dettes sur acquisitions de valeurs mobilières de placement', type: 'tiers'),
        Account(id: '465', number: '465', name: 'Créances sur cessions de valeurs mobilières de placement', type: 'tiers'),
        Account(id: '467', number: '467', name: 'Divers comptes débiteurs et produits à recevoir', type: 'tiers'),
        Account(id: '468', number: '468', name: 'Divers comptes créditeurs et charges à payer', type: 'tiers'),

        Account(id: '47', number: '47', name: 'Comptes transitoires ou d\'attente', type: 'tiers'),
        Account(id: '471', number: '471', name: 'Comptes d\'attente (471 à 473)', type: 'tiers'),
        Account(id: '474', number: '474', name: 'Différences d\'évaluation - Actif', type: 'tiers'),
        Account(id: '4741', number: '4741', name: 'Différences d\'évaluation sur instruments financiers à terme - Actif', type: 'tiers'),
        Account(id: '4742', number: '4742', name: 'Différences d\'évaluation sur jetons détenus - Actif', type: 'tiers'),
        Account(id: '4746', number: '4746', name: 'Différences d\'évaluation de jetons sur des passifs - Actif', type: 'tiers'),
        Account(id: '475', number: '475', name: 'Différences d\'évaluation - Passif', type: 'tiers'),
        Account(id: '4751', number: '4751', name: 'Différences d\'évaluation sur instruments financiers à terme - Passif', type: 'tiers'),
        Account(id: '4752', number: '4752', name: 'Différences d\'évaluation sur jetons détenus - Passif', type: 'tiers'),
        Account(id: '4756', number: '4756', name: 'Différences d\'évaluation de jetons sur des passifs - Passif', type: 'tiers'),
        Account(id: '476', number: '476', name: 'Différence de conversion - Actif', type: 'tiers'),
        Account(id: '4761', number: '4761', name: 'Diminution des créances', type: 'tiers'),
        Account(id: '4762', number: '4762', name: 'Augmentation des dettes', type: 'tiers'),
        Account(id: '4768', number: '4768', name: 'Différences compensées par couverture de change', type: 'tiers'),
        Account(id: '477', number: '477', name: 'Différences de conversion - Passif', type: 'tiers'),
        Account(id: '4771', number: '4771', name: 'Augmentation des créances', type: 'tiers'),
        Account(id: '4772', number: '4772', name: 'Diminution des dettes', type: 'tiers'),
        Account(id: '4778', number: '4778', name: 'Différences compensées par couverture de change', type: 'tiers'),
        Account(id: '478', number: '478', name: 'Autres comptes transitoires', type: 'tiers'),
        Account(id: '4781', number: '4781', name: 'Mali de fusion sur actif circulant', type: 'tiers'),

        Account(id: '48', number: '48', name: 'Comptes de régularisation', type: 'tiers'),
        Account(id: '481', number: '481', name: 'Frais d\'émission des emprunts', type: 'tiers'),
        Account(id: '486', number: '486', name: 'Charges constatées d\'avance', type: 'tiers'),
        Account(id: '487', number: '487', name: 'Produits constatés d\'avance', type: 'tiers'),
        Account(id: '4871', number: '4871', name: 'Produits constatés d\'avance sur jetons émis', type: 'tiers'),
        Account(id: '488', number: '488', name: 'Comptes de répartition périodique des charges et des produits', type: 'tiers'),
        Account(id: '4886', number: '4886', name: 'Charges', type: 'tiers'),
        Account(id: '4887', number: '4887', name: 'Produits', type: 'tiers'),

        Account(id: '49', number: '49', name: 'Dépréciations des comptes de tiers', type: 'tiers'),
        Account(id: '491', number: '491', name: 'Dépréciations des comptes de clients', type: 'tiers'),

        // --- SUITE CLASSE 4 : COMPTES DE TIERS (Page 7) ---
        Account(id: '495', number: '495', name: 'Dépréciations des comptes du groupe et des associés', type: 'tiers'),
        Account(id: '4951', number: '4951', name: 'Comptes du groupe', type: 'tiers'),
        Account(id: '4958', number: '4958', name: 'Opérations faites en commun et en GIE', type: 'tiers'),

        Account(id: '496', number: '496', name: 'Dépréciations des comptes de débiteurs divers', type: 'tiers'),
        Account(id: '4962', number: '4962', name: 'Créances sur cessions d\'immobilisations', type: 'tiers'),
        Account(id: '4965', number: '4965', name: 'Créances sur cessions de valeurs mobilières de placement', type: 'tiers'),
        Account(id: '4967', number: '4967', name: 'Autres comptes débiteurs', type: 'tiers'),

        // --- CLASSE 5 : COMPTES FINANCIERS ---
        Account(id: '50', number: '50', name: 'Valeurs mobilières de placement', type: 'banque'),
        Account(id: '501', number: '501', name: 'Parts dans des entreprises liées', type: 'banque'),
        Account(id: '502', number: '502', name: 'Actions propres', type: 'banque'),
        Account(id: '503', number: '503', name: 'Actions', type: 'banque'),
        Account(id: '504', number: '504', name: 'Autres titres conférant un droit de propriété', type: 'banque'),
        Account(id: '505', number: '505', name: 'Obligations et bons d\'émission', type: 'banque'),
        Account(id: '506', number: '506', name: 'Obligations et bons du Trésor et bons de caisse', type: 'banque'),
        Account(id: '507', number: '507', name: 'Bons de souscription', type: 'banque'),
        Account(id: '508', number: '508', name: 'Autres valeurs mobilières de placement et créances assimilées', type: 'banque'),
        Account(id: '5081', number: '5081', name: 'Autres valeurs mobilières', type: 'banque'),
        Account(id: '5088', number: '5088', name: 'Intérêts courus sur valeurs mobilières de placement', type: 'banque'),
        Account(id: '509', number: '509', name: 'Versements restant à effectuer sur valeurs mobilières de placement non libérées', type: 'banque'),

        Account(id: '51', number: '51', name: 'Banque, établissements financiers et assimilés', type: 'banque'),
        Account(id: '511', number: '511', name: 'Valeurs à l\'encaissement', type: 'banque'),
        Account(id: '5112', number: '5112', name: 'Chèques à encaisser', type: 'banque'),
        Account(id: '5115', number: '5115', name: 'Cartes bancaires à encaisser', type: 'banque'),
        Account(id: '5118', number: '5118', name: 'Autres valeurs à l\'encaissement', type: 'banque'),
        Account(id: '512', number: '512', name: 'Banques', type: 'banque'),
        Account(id: '514', number: '514', name: 'Chèques postaux', type: 'banque'),
        Account(id: '515', number: '515', name: 'Caisses des dépôts et consignations', type: 'banque'),
        Account(id: '517', number: '517', name: 'Autres organismes financiers', type: 'banque'),
        Account(id: '518', number: '518', name: 'Intérêts courus', type: 'banque'),
        Account(id: '5181', number: '5181', name: 'Intérêts courus à payer', type: 'banque'),
        Account(id: '5188', number: '5188', name: 'Intérêts courus à recevoir', type: 'banque'),
        Account(id: '519', number: '519', name: 'Concours bancaires courants', type: 'banque'),

        Account(id: '52', number: '52', name: 'Instruments financiers à terme', type: 'banque'),

        Account(id: '53', number: '53', name: 'Caisse', type: 'banque'),
        Account(id: '531', number: '531', name: 'Caisse siège social', type: 'banque'),
        Account(id: '532', number: '532', name: 'Caisse succursale (ou agence) A', type: 'banque'),
        Account(id: '533', number: '533', name: 'Caisse succursale (ou agence) B', type: 'banque'),

        Account(id: '54', number: '54', name: 'Régies d\'avances et accréditifs', type: 'banque'),

        Account(id: '58', number: '58', name: 'Virements internes', type: 'banque'),

        Account(id: '59', number: '59', name: 'Dépréciations des comptes financiers', type: 'banque'),
        Account(id: '590', number: '590', name: 'Dépréciations des valeurs mobilières de placement', type: 'banque'),
        Account(id: '5903', number: '5903', name: 'Actions', type: 'banque'),
        Account(id: '5904', number: '5904', name: 'Autres titres conférant un droit de propriété', type: 'banque'),
        Account(id: '5906', number: '5906', name: 'Obligations et bons du Trésor et bons de caisse', type: 'banque'),
        Account(id: '5908', number: '5908', name: 'Autres valeurs mobilières de placement et créances assimilées', type: 'banque'),

        // --- CLASSE 6 : COMPTES DE CHARGES ---
        Account(id: '60', number: '60', name: 'Achats (sauf 603)', type: 'charge'),
        Account(id: '601', number: '601', name: 'Achats de matières premières (et fournitures)', type: 'charge'),
        Account(id: '6011', number: '6011', name: 'Matières (ou groupe) A', type: 'charge'),
        Account(id: '6012', number: '6012', name: 'Matières (ou groupe) B', type: 'charge'),
        Account(id: '6017', number: '6017', name: 'Fournitures A, B...', type: 'charge'),

        Account(id: '602', number: '602', name: 'Achats d\'autres approvisionnements', type: 'charge'),
        Account(id: '6021', number: '6021', name: 'Matières consommables', type: 'charge'),
        Account(id: '6022', number: '6022', name: 'Fournitures consommables', type: 'charge'),
        Account(id: '60221', number: '60221', name: 'Combustibles', type: 'charge'),
        Account(id: '60222', number: '60222', name: 'Produits d\'entretien', type: 'charge'),
        Account(id: '60223', number: '60223', name: 'Fournitures d\'atelier et d\'usine', type: 'charge'),
        Account(id: '60224', number: '60224', name: 'Fournitures de magasin', type: 'charge'),
        Account(id: '60225', number: '60225', name: 'Fournitures de bureau', type: 'charge'),
        Account(id: '6026', number: '6026', name: 'Emballages', type: 'charge'),
        Account(id: '60261', number: '60261', name: 'Emballages perdus', type: 'charge'),
        Account(id: '60265', number: '60265', name: 'Emballages récupérables non identifiables', type: 'charge'),
        Account(id: '60267', number: '60267', name: 'Emballages à usage mixte', type: 'charge'),

        Account(id: '603', number: '603', name: 'Variations des stocks (approvisionnements et marchandises)', type: 'charge'),
        Account(id: '6031', number: '6031', name: 'Variation des stocks de matières premières et fournitures', type: 'charge'),
        Account(id: '6032', number: '6032', name: 'Variation des stocks des autres approvisionnements', type: 'charge'),
        Account(id: '6037', number: '6037', name: 'Variation des stocks de marchandises', type: 'charge'),

        Account(id: '604', number: '604', name: 'Achats d\'études et prestations de services', type: 'charge'),

        Account(id: '605', number: '605', name: 'Achats de matériels, équipements et travaux', type: 'charge'),

        Account(id: '606', number: '606', name: 'Achats non stockés de matières et fournitures', type: 'charge'),
        Account(id: '6061', number: '6061', name: 'Fournitures non stockables (eau, énergie)', type: 'charge'),
        Account(id: '6063', number: '6063', name: 'Fournitures d\'entretien et de petit équipement', type: 'charge'),
        Account(id: '6064', number: '6064', name: 'Fournitures administratives', type: 'charge'),
        Account(id: '6068', number: '6068', name: 'Autres matières et fournitures', type: 'charge'),

        Account(id: '607', number: '607', name: 'Achats de marchandises', type: 'charge'),
        Account(id: '6071', number: '6071', name: 'Marchandises (ou groupe) A', type: 'charge'),
        Account(id: '6072', number: '6072', name: 'Marchandises (ou groupe) B', type: 'charge'),

        Account(id: '608', number: '608', name: '(Compte à la disposition des entités pour regrouper les frais accessoires sur achats)', type: 'charge'),

        Account(id: '609', number: '609', name: 'Rabais, remises et ristournes obtenus sur achats', type: 'charge'),
        Account(id: '6091', number: '6091', name: 'sur achats de matières premières et fournitures', type: 'charge'),
        Account(id: '6092', number: '6092', name: 'sur achats d\'autres approvisionnements', type: 'charge'),
        Account(id: '6094', number: '6094', name: 'sur achats d\'études et prestations de services', type: 'charge'),
        Account(id: '6095', number: '6095', name: 'sur achats de matériels, équipements et travaux', type: 'charge'),
        Account(id: '6096', number: '6096', name: 'sur achats non stockés de matières et fournitures', type: 'charge'),
        Account(id: '6097', number: '6097', name: 'sur achats de marchandises', type: 'charge'),
        Account(id: '6098', number: '6098', name: 'Rabais, remises et ristournes non affectés', type: 'charge'),

        Account(id: '61', number: '61', name: 'Services extérieurs', type: 'charge'),
        Account(id: '611', number: '611', name: 'Sous-traitance générale', type: 'charge'),
        Account(id: '612', number: '612', name: 'Redevances de crédit-bail', type: 'charge'),
        Account(id: '6122', number: '6122', name: 'Crédit-bail mobilier', type: 'charge'),
        Account(id: '6125', number: '6125', name: 'Crédit-bail immobilier', type: 'charge'),
        Account(id: '613', number: '613', name: 'Locations', type: 'charge'),
        Account(id: '6132', number: '6132', name: 'Locations immobilières', type: 'charge'),
        Account(id: '6135', number: '6135', name: 'Locations mobilières', type: 'charge'),
        Account(id: '6136', number: '6136', name: 'Malus sur locations de voitures de tourisme', type: 'charge'),
        Account(id: '614', number: '614', name: 'Charges locatives et de copropriété', type: 'charge'),
        Account(id: '615', number: '615', name: 'Entretien et réparations', type: 'charge'),
        Account(id: '6152', number: '6152', name: 'sur biens immobiliers', type: 'charge'),
        Account(id: '6155', number: '6155', name: 'sur biens mobiliers', type: 'charge'),
        Account(id: '6156', number: '6156', name: 'Maintenance', type: 'charge'),
        Account(id: '616', number: '616', name: 'Primes d\'assurances', type: 'charge'),
        Account(id: '6161', number: '6161', name: 'Multirisques', type: 'charge'),
        Account(id: '6162', number: '6162', name: 'Assurance obligatoire dommage construction', type: 'charge'),
        Account(id: '6163', number: '6163', name: 'Assurance transport', type: 'charge'),
        Account(id: '6164', number: '6164', name: 'Risques d\'exploitation', type: 'charge'),
        Account(id: '6165', number: '6165', name: 'Insolvabilité clients', type: 'charge'),
        Account(id: '617', number: '617', name: 'Etudes et recherches', type: 'charge'),
        Account(id: '618', number: '618', name: 'Divers', type: 'charge'),
        Account(id: '6181', number: '6181', name: 'Documentation générale', type: 'charge'),
        Account(id: '6183', number: '6183', name: 'Documentation technique', type: 'charge'),
        Account(id: '6185', number: '6185', name: 'Frais de colloques, séminaires, conférences', type: 'charge'),
        Account(id: '619', number: '619', name: 'Rabais, remises et ristournes obtenus sur services extérieurs', type: 'charge'),

        Account(id: '62', number: '62', name: 'Autres services extérieurs', type: 'charge'),
        Account(id: '621', number: '621', name: 'Personnel extérieur à l\'entité', type: 'charge'),
        Account(id: '6211', number: '6211', name: 'Personnel intérimaire', type: 'charge'),
        Account(id: '6214', number: '6214', name: 'Personnel détaché ou prêté à l\'entité', type: 'charge'),
        Account(id: '622', number: '622', name: 'Rémunérations d\'intermédiaires et honoraires', type: 'charge'),
        Account(id: '6221', number: '6221', name: 'Commissions et courtages sur achats', type: 'charge'),
        Account(id: '6222', number: '6222', name: 'Commissions et courtages sur ventes', type: 'charge'),
        Account(id: '6224', number: '6224', name: 'Rémunérations des apporteurs de capitaux', type: 'charge'),
        Account(id: '6225', number: '6225', name: 'Indemnités de numéraire', type: 'charge'),
        Account(id: '6226', number: '6226', name: 'Honoraires', type: 'charge'),
        Account(id: '6227', number: '6227', name: 'Frais d\'actes et de contentieux', type: 'charge'),
        Account(id: '6228', number: '6228', name: 'Divers', type: 'charge'),
        Account(id: '623', number: '623', name: 'Publicité, publications, relations publiques', type: 'charge'),
        Account(id: '6231', number: '6231', name: 'Annonces et insertions', type: 'charge'),
        Account(id: '6232', number: '6232', name: 'Echantillons', type: 'charge'),
        Account(id: '6233', number: '6233', name: 'Foires et expositions', type: 'charge'),
        Account(id: '6234', number: '6234', name: 'Cadeaux à la clientèle', type: 'charge'),
        Account(id: '6235', number: '6235', name: 'Primes', type: 'charge'),
        Account(id: '6236', number: '6236', name: 'Catalogues et imprimés publicitaires', type: 'charge'),
        Account(id: '6237', number: '6237', name: 'Publications', type: 'charge'),
        Account(id: '6238', number: '6238', name: 'Divers (pourboires, dons courants...)', type: 'charge'),
        Account(id: '624', number: '624', name: 'Transports de biens et transports collectifs du personnel', type: 'charge'),
        Account(id: '6241', number: '6241', name: 'Transports sur achats', type: 'charge'),
        Account(id: '6242', number: '6242', name: 'Transports sur ventes', type: 'charge'),
        Account(id: '6243', number: '6243', name: 'Transports entre établissements ou chantiers', type: 'charge'),
        Account(id: '6244', number: '6244', name: 'Transports administratifs', type: 'charge'),
        Account(id: '6247', number: '6247', name: 'Transports collectifs du personnel', type: 'charge'),

        Account(id: '6248', number: '6248', name: 'Divers', type: 'charge'),

        Account(id: '625', number: '625', name: 'Déplacements, missions et réceptions', type: 'charge'),
        Account(id: '6251', number: '6251', name: 'Voyages et déplacements', type: 'charge'),
        Account(id: '6255', number: '6255', name: 'Frais de déménagement', type: 'charge'),
        Account(id: '6256', number: '6256', name: 'Missions', type: 'charge'),
        Account(id: '6257', number: '6257', name: 'Réceptions', type: 'charge'),

        Account(id: '626', number: '626', name: 'Frais postaux et de télécommunications', type: 'charge'),

        Account(id: '627', number: '627', name: 'Services bancaires et assimilés', type: 'charge'),
        Account(id: '6271', number: '6271', name: 'Frais sur titres (achat, vente, garde)', type: 'charge'),
        Account(id: '6272', number: '6272', name: 'Commissions et frais sur émission d\'emprunts', type: 'charge'),
        Account(id: '6275', number: '6275', name: 'Frais sur effets', type: 'charge'),
        Account(id: '6278', number: '6278', name: 'Autres frais et commissions bancaires', type: 'charge'),

        Account(id: '628', number: '628', name: 'Divers', type: 'charge'),
        Account(id: '6281', number: '6281', name: 'Concours divers (cotisations...)', type: 'charge'),
        Account(id: '6284', number: '6284', name: 'Frais de recrutement de personnel', type: 'charge'),
        Account(id: '6285', number: '6285', name: 'Frais de jetons émis (plateformes de services)', type: 'charge'),

        Account(id: '629', number: '629', name: 'Rabais, remises et ristournes obtenus sur autres services extérieurs', type: 'charge'),

        Account(id: '63', number: '63', name: 'Impôts, taxes et versements assimilés', type: 'charge'),
        Account(id: '631', number: '631', name: 'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)', type: 'charge'),
        Account(id: '6311', number: '6311', name: 'Taxe sur les salaires', type: 'charge'),
        Account(id: '6312', number: '6312', name: 'Taxe d\'apprentissage', type: 'charge'),
        Account(id: '6313', number: '6313', name: 'Participation des employeurs à la formation professionnelle continue', type: 'charge'),
        Account(id: '6314', number: '6314', name: 'Cotisation pour la valeur ajoutée des entreprises', type: 'charge'),
        Account(id: '6318', number: '6318', name: 'Autres', type: 'charge'),
        Account(id: '633', number: '633', name: 'Impôts, taxes et versements assimilés sur rémunérations (autres organismes)', type: 'charge'),
        Account(id: '6331', number: '6331', name: 'Versement mobilité', type: 'charge'),
        Account(id: '6332', number: '6332', name: 'Cotisation logement', type: 'charge'),
        Account(id: '6333', number: '6333', name: 'Participation des employeurs à la formation professionnelle continue', type: 'charge'),
        Account(id: '6338', number: '6338', name: 'Autres impôts, taxes et versements assimilés sur rémunérations', type: 'charge'),
        Account(id: '635', number: '635', name: 'Autres impôts, taxes et versements assimilés (administrations des impôts)', type: 'charge'),
        Account(id: '6351', number: '6351', name: 'Impôts directs (sauf impôts sur les bénéfices)', type: 'charge'),
        Account(id: '63511', number: '63511', name: 'Contribution économique territoriale', type: 'charge'),
        Account(id: '63512', number: '63512', name: 'Taxes foncières', type: 'charge'),
        Account(id: '63513', number: '63513', name: 'Autres impôts locaux', type: 'charge'),
        Account(id: '63514', number: '63514', name: 'Taxe sur les véhicules des sociétés', type: 'charge'),
        Account(id: '6352', number: '6352', name: 'Taxe sur le chiffre d\'affaires non récupérable', type: 'charge'),
        Account(id: '6353', number: '6353', name: 'Impôts indirects', type: 'charge'),
        Account(id: '6354', number: '6354', name: 'Droits d\'enregistrement et de timbre', type: 'charge'),
        Account(id: '63541', number: '63541', name: 'Droits de mutation', type: 'charge'),
        Account(id: '6358', number: '6358', name: 'Autres droits', type: 'charge'),
        Account(id: '637', number: '637', name: 'Autres impôts, taxes et versements assimilés (autres organismes)', type: 'charge'),

        Account(id: '64', number: '64', name: 'Charges de personnel', type: 'charge'),
        Account(id: '641', number: '641', name: 'Rémunérations du personnel', type: 'charge'),
        Account(id: '6411', number: '6411', name: 'Salaires, appointements', type: 'charge'),
        Account(id: '6412', number: '6412', name: 'Congés payés', type: 'charge'),
        Account(id: '6413', number: '6413', name: 'Primes et gratifications', type: 'charge'),
        Account(id: '6414', number: '6414', name: 'Indemnités et avantages divers', type: 'charge'),
        Account(id: '6415', number: '6415', name: 'Supplément familial', type: 'charge'),
        Account(id: '644', number: '644', name: 'Rémunération du travail de l\'exploitant', type: 'charge'),
        Account(id: '645', number: '645', name: 'Charges de sécurité sociale et de prévoyance', type: 'charge'),
        Account(id: '6451', number: '6451', name: 'Cotisations à la sécurité sociale', type: 'charge'),
        Account(id: '6452', number: '6452', name: 'Cotisations aux mutuelles', type: 'charge'),
        Account(id: '6453', number: '6453', name: 'Cotisations aux caisses de retraites', type: 'charge'),
        Account(id: '6454', number: '6454', name: 'Cotisations aux organismes de prévoyance', type: 'charge'),
        Account(id: '6458', number: '6458', name: 'Cotisations aux autres organismes sociaux', type: 'charge'),
        Account(id: '647', number: '647', name: 'Autres charges sociales', type: 'charge'),
        Account(id: '6471', number: '6471', name: 'Prestations directes', type: 'charge'),
        Account(id: '6472', number: '6472', name: 'Versements aux comités sociaux et économiques', type: 'charge'),
        Account(id: '6473', number: '6473', name: 'Versements aux œuvres sociales', type: 'charge'),
        Account(id: '6474', number: '6474', name: 'Versements aux autres œuvres sociales', type: 'charge'),
        Account(id: '6475', number: '6475', name: 'Médecine du travail, pharmacie', type: 'charge'),
        Account(id: '648', number: '648', name: 'Autres charges de personnel', type: 'charge'),

        Account(id: '65', number: '65', name: 'Autres charges de gestion courante', type: 'charge'),
        Account(id: '651', number: '651', name: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires', type: 'charge'),
        Account(id: '6511', number: '6511', name: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels', type: 'charge'),
        Account(id: '6516', number: '6516', name: 'Droits d\'auteur et de reproduction', type: 'charge'),

        Account(id: '6518', number: '6518', name: 'Autres droits et valeurs similaires', type: 'charge'),

        Account(id: '653', number: '653', name: 'Jetons de présence', type: 'charge'),

        Account(id: '654', number: '654', name: 'Pertes sur créances irrécouvrables', type: 'charge'),
        Account(id: '6541', number: '6541', name: 'Créances de l\'exercice', type: 'charge'),
        Account(id: '6544', number: '6544', name: 'Créances des exercices antérieurs', type: 'charge'),

        Account(id: '655', number: '655', name: 'Quote-part de résultat sur opérations faites en commun', type: 'charge'),
        Account(id: '6551', number: '6551', name: 'Quote-part de bénéfice transférée (comptabilité du gérant)', type: 'charge'),
        Account(id: '6555', number: '6555', name: 'Quote-part de perte supportée (comptabilité des associés non gérants)', type: 'charge'),

        Account(id: '656', number: '656', name: 'Pertes de valeur des jetons émis (plateformes de services)', type: 'charge'),

        Account(id: '658', number: '658', name: 'Charges diverses de gestion courante', type: 'charge'),

        Account(id: '66', number: '66', name: 'Charges financières', type: 'charge'),
        Account(id: '661', number: '661', name: 'Charges d\'intérêts', type: 'charge'),
        Account(id: '6611', number: '6611', name: 'Intérêts des emprunts et dettes', type: 'charge'),
        Account(id: '66116', number: '66116', name: 'des emprunts et dettes assimilées', type: 'charge'),
        Account(id: '66117', number: '66117', name: 'des dettes rattachées à des participations', type: 'charge'),
        Account(id: '6615', number: '6615', name: 'Intérêts des comptes courants et des dépôts créditeurs', type: 'charge'),
        Account(id: '6616', number: '6616', name: 'Intérêts bancaires et sur opérations de financement (escompte...)', type: 'charge'),
        Account(id: '6617', number: '6617', name: 'Intérêts des obligations cautionnées', type: 'charge'),
        Account(id: '6618', number: '6618', name: 'Intérêts des autres dettes', type: 'charge'),

        Account(id: '664', number: '664', name: 'Pertes sur créances rattachées à des participations', type: 'charge'),

        Account(id: '665', number: '665', name: 'Escomptes accordés', type: 'charge'),

        Account(id: '666', number: '666', name: 'Pertes de change financières', type: 'charge'),

        Account(id: '667', number: '667', name: 'Charges nettes sur cessions de valeurs mobilières de placement', type: 'charge'),

        Account(id: '668', number: '668', name: 'Autres charges financières', type: 'charge'),

        Account(id: '67', number: '67', name: 'Charges exceptionnelles', type: 'charge'),
        Account(id: '671', number: '671', name: 'Charges exceptionnelles sur opérations de gestion', type: 'charge'),
        Account(id: '6712', number: '6712', name: 'Pénalités sur marchés (et dédits payés sur achats et ventes)', type: 'charge'),
        Account(id: '6713', number: '6713', name: 'Dons, libéralités', type: 'charge'),
        Account(id: '6714', number: '6714', name: 'Créances devenues irrécouvrables dans l\'exercice', type: 'charge'),
        Account(id: '6715', number: '6715', name: 'Subventions d\'équilibre accordées', type: 'charge'),
        Account(id: '6717', number: '6717', name: 'Rappels d\'impôts (autres qu\'impôts sur les bénéfices)', type: 'charge'),
        Account(id: '6718', number: '6718', name: 'Autres charges exceptionnelles sur opérations de gestion', type: 'charge'),

        Account(id: '672', number: '672', name: '(Compte à la disposition des entités pour enregistrer, en cours d\'exercice, les charges sur exercices antérieurs)', type: 'charge'),

        Account(id: '675', number: '675', name: 'Valeurs comptables des éléments d\'actif cédés', type: 'charge'),
        Account(id: '6751', number: '6751', name: 'Immobilisations incorporelles', type: 'charge'),
        Account(id: '6752', number: '6752', name: 'Immobilisations corporelles', type: 'charge'),
        Account(id: '6756', number: '6756', name: 'Immobilisations financières', type: 'charge'),

        Account(id: '678', number: '678', name: 'Autres charges exceptionnelles', type: 'charge'),
        Account(id: '6781', number: '6781', name: 'Malus provenant de l\'annulation d\'actions propres', type: 'charge'),
        Account(id: '6782', number: '6782', name: 'Lots', type: 'charge'),
        Account(id: '6783', number: '6783', name: 'Mali de fusion', type: 'charge'),
        Account(id: '6788', number: '6788', name: 'Charges exceptionnelles diverses', type: 'charge'),

        Account(id: '68', number: '68', name: 'Dotations aux amortissements, dépréciations et provisions', type: 'charge'),
        Account(id: '681', number: '681', name: 'Dotations aux amortissements, dépréciations et provisions (à inscrire dans les charges d\'exploitation)', type: 'charge'),
        Account(id: '6811', number: '6811', name: 'Dotations aux amortissements sur immobilisations incorporelles et corporelles', type: 'charge'),
        Account(id: '68111', number: '68111', name: 'Immobilisations incorporelles', type: 'charge'),
        Account(id: '68112', number: '68112', name: 'Immobilisations corporelles', type: 'charge'),
        Account(id: '6815', number: '6815', name: 'Dotations aux provisions d\'exploitation', type: 'charge'),
        Account(id: '6816', number: '6816', name: 'Dotations aux dépréciations des immobilisations incorporelles et corporelles', type: 'charge'),
        Account(id: '68161', number: '68161', name: 'Immobilisations incorporelles', type: 'charge'),
        Account(id: '68162', number: '68162', name: 'Immobilisations corporelles', type: 'charge'),
        Account(id: '6817', number: '6817', name: 'Dotations aux dépréciations des actifs circulants', type: 'charge'),
        Account(id: '68173', number: '68173', name: 'Stocks et en-cours', type: 'charge'),
        Account(id: '68174', number: '68174', name: 'Créances', type: 'charge'),

        Account(id: '686', number: '686', name: 'Dotations aux dépréciations et provisions (à inscrire dans les charges financières)', type: 'charge'),
        Account(id: '6861', number: '6861', name: 'Dotations aux amortissements des primes d\'émission de titres à revenu fixe', type: 'charge'),
        Account(id: '6865', number: '6865', name: 'Dotations aux provisions financières', type: 'charge'),
        Account(id: '6866', number: '6866', name: 'Dotations aux dépréciations des éléments financiers', type: 'charge'),
        Account(id: '68662', number: '68662', name: 'Immobilisations financières', type: 'charge'),
        Account(id: '68665', number: '68665', name: 'Valeurs mobilières de placement', type: 'charge'),

        Account(id: '687', number: '687', name: 'Dotations aux dépréciations et provisions (à inscrire dans les charges exceptionnelles)', type: 'charge'),
        Account(id: '6871', number: '6871', name: 'Dotations aux provisions réglementées (exploitation)', type: 'charge'),
        Account(id: '6872', number: '6872', name: 'Dotations aux provisions réglementées (immobilisations)', type: 'charge'),
        Account(id: '68725', number: '68725', name: 'Amortissements dérogatoires', type: 'charge'),
        Account(id: '6873', number: '6873', name: 'Dotations aux provisions réglementées (stocks)', type: 'charge'),
        Account(id: '6874', number: '6874', name: 'Dotations aux autres provisions réglementées', type: 'charge'),
        Account(id: '6875', number: '6875', name: 'Dotations aux provisions exceptionnelles', type: 'charge'),
        Account(id: '6876', number: '6876', name: 'Dotations aux dépréciations exceptionnelles', type: 'charge'),

        Account(id: '69', number: '69', name: 'Participation des salariés - Impôts sur les bénéfices et assimilés', type: 'charge'),
        Account(id: '691', number: '691', name: 'Participation des salariés aux résultats', type: 'charge'),
        Account(id: '695', number: '695', name: 'Impôts sur les bénéfices', type: 'charge'),
        Account(id: '6951', number: '6951', name: 'Impôts dus en France', type: 'charge'),

        Account(id: '6952', number: '6952', name: 'Contribution additionnelle à l\'impôt sur les bénéfices', type: 'charge'),
        Account(id: '6954', number: '6954', name: 'Impôts dus à l\'étranger', type: 'charge'),
        Account(id: '696', number: '696', name: 'Suppléments d\'impôt sur les sociétés liés aux distributions', type: 'charge'),
        Account(id: '698', number: '698', name: 'Intégration fiscale', type: 'charge'),
        Account(id: '6981', number: '6981', name: 'Intégration fiscale - Charges', type: 'charge'),
        Account(id: '6989', number: '6989', name: 'Intégration fiscale - Produits', type: 'produit'),
        Account(id: '699', number: '699', name: 'Produits - Report en arrière des déficits', type: 'produit'),

        // --- CLASSE 7 : COMPTES DE PRODUITS ---
        Account(id: '70', number: '70', name: 'Ventes de produits fabriqués, prestations de services, marchandises', type: 'produit'),
        Account(id: '701', number: '701', name: 'Ventes de produits finis', type: 'produit'),
        Account(id: '702', number: '702', name: 'Ventes de produits intermédiaires', type: 'produit'),
        Account(id: '703', number: '703', name: 'Ventes de produits résiduels', type: 'produit'),
        Account(id: '704', number: '704', name: 'Travaux', type: 'produit'),
        Account(id: '705', number: '705', name: 'Études', type: 'produit'),
        Account(id: '706', number: '706', name: 'Prestations de services', type: 'produit'),
        Account(id: '707', number: '707', name: 'Ventes de marchandises', type: 'produit'),
        Account(id: '708', number: '708', name: 'Produits des activités annexes', type: 'produit'),
        Account(id: '7081', number: '7081', name: 'Produits des services exploités dans l\'intérêt du personnel', type: 'produit'),
        Account(id: '7082', number: '7082', name: 'Commissions et courtages', type: 'produit'),
        Account(id: '7083', number: '7083', name: 'Locations diverses', type: 'produit'),
        Account(id: '7084', number: '7084', name: 'Mise à disposition de personnel facturée', type: 'produit'),
        Account(id: '7085', number: '7085', name: 'Ports et frais accessoires facturés', type: 'produit'),
        Account(id: '7086', number: '7086', name: 'Bonis sur reprises d\'emballages consignés', type: 'produit'),
        Account(id: '7088', number: '7088', name: 'Autres produits d\'activités annexes', type: 'produit'),
        Account(id: '709', number: '709', name: 'Rabais, remises et ristournes accordés par l\'entité', type: 'produit'),

        Account(id: '71', number: '71', name: 'Production stockée (ou déstockage)', type: 'produit'),
        Account(id: '713', number: '713', name: 'Variation des stocks (en-cours de production, produits)', type: 'produit'),
        Account(id: '7133', number: '7133', name: 'Variation des en-cours de production de biens', type: 'produit'),
        Account(id: '7134', number: '7134', name: 'Variation des en-cours de production de services', type: 'produit'),
        Account(id: '7135', number: '7135', name: 'Variation des stocks de produits', type: 'produit'),

        Account(id: '72', number: '72', name: 'Production immobilisée', type: 'produit'),
        Account(id: '721', number: '721', name: 'Immobilisations incorporelles', type: 'produit'),
        Account(id: '722', number: '722', name: 'Immobilisations corporelles', type: 'produit'),

        Account(id: '74', number: '74', name: 'Subventions d\'exploitation', type: 'produit'),

        Account(id: '75', number: '75', name: 'Autres produits de gestion courante', type: 'produit'),
        Account(id: '751', number: '751', name: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires', type: 'produit'),
        Account(id: '7511', number: '7511', name: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels', type: 'produit'),
        Account(id: '7516', number: '7516', name: 'Droits d\'auteur et de reproduction', type: 'produit'),
        Account(id: '7518', number: '7518', name: 'Autres droits et valeurs similaires', type: 'produit'),
        Account(id: '753', number: '753', name: 'Jetons de présence et rémunérations d\'administrateurs, gérants...', type: 'produit'),
        Account(id: '754', number: '754', name: 'Collectes de jetons (plateformes de services)', type: 'produit'),
        Account(id: '755', number: '755', name: 'Quote-part de résultat sur opérations faites en commun', type: 'produit'),
        Account(id: '7551', number: '7551', name: 'Quote-part de perte transférée (comptabilité du gérant)', type: 'produit'),
        Account(id: '7555', number: '7555', name: 'Quote-part de bénéfice attribuée (comptabilité des associés non gérants)', type: 'produit'),
        Account(id: '756', number: '756', name: 'Gains de valeur des jetons émis (plateformes de services)', type: 'produit'),
        Account(id: '758', number: '758', name: 'Produits divers de gestion courante', type: 'produit'),
        Account(id: '7581', number: '7581', name: 'Indemnités d\'assurance (activités courantes)', type: 'produit'),
        Account(id: '7582', number: '7582', name: 'Boni provenant de l\'annulation d\'actions propres', type: 'produit'),
        Account(id: '7586', number: '7586', name: 'Lots', type: 'produit'),

        Account(id: '7587', number: '7587', name: 'Indemnités d’assurance', type: 'produit'),
        Account(id: '7588', number: '7588', name: 'Opérations de constitution ou liquidation des fiducies', type: 'produit'),

        Account(id: '76', number: '76', name: 'Produits financiers', type: 'produit'),
        Account(id: '761', number: '761', name: 'Produits de participations', type: 'produit'),
        Account(id: '7611', number: '7611', name: 'Revenus des titres de participation', type: 'produit'),
        Account(id: '7612', number: '7612', name: 'Produits de la fiducie, résultat de la période', type: 'produit'),
        Account(id: '7616', number: '7616', name: 'Revenus sur autres formes de participation', type: 'produit'),
        Account(id: '7617', number: '7617', name: 'Revenus des créances rattachées à des participations', type: 'produit'),

        Account(id: '762', number: '762', name: 'Produits des autres immobilisations financières', type: 'produit'),
        Account(id: '7621', number: '7621', name: 'Revenus des titres immobilisés', type: 'produit'),
        Account(id: '7626', number: '7626', name: 'Revenus des prêts', type: 'produit'),
        Account(id: '7627', number: '7627', name: 'Revenus des créances immobilisées', type: 'produit'),

        Account(id: '763', number: '763', name: 'Revenus des autres créances', type: 'produit'),
        Account(id: '7631', number: '7631', name: 'Revenus des créances commerciales', type: 'produit'),
        Account(id: '7638', number: '7638', name: 'Revenus des créances diverses', type: 'produit'),

        Account(id: '764', number: '764', name: 'Revenus des valeurs mobilières de placement', type: 'produit'),

        Account(id: '765', number: '765', name: 'Escomptes obtenus', type: 'produit'),

        Account(id: '766', number: '766', name: 'Gains de change financiers', type: 'produit'),

        Account(id: '767', number: '767', name: 'Produits sur cession d’éléments financiers', type: 'produit'),
        Account(id: '7671', number: '7671', name: 'Produits des cessions d’immobilisations financières', type: 'produit'),
        Account(id: '7672', number: '7672', name: 'Produits nets sur cessions de titres immobilisés de l’activité de portefeuille', type: 'produit'),
        Account(id: '7673', number: '7673', name: 'Produits nets sur cessions de valeurs mobilières de placement', type: 'produit'),
        Account(id: '7674', number: '7674', name: 'Produits nets sur cessions de jetons', type: 'produit'),

        Account(id: '768', number: '768', name: 'Autres produits financiers', type: 'produit'),
        Account(id: '7683', number: '7683', name: 'Bonis provenant du rachat par l’entreprise d’actions et d’obligations émises par elle-même', type: 'produit'),

        Account(id: '77', number: '77', name: 'Produits exceptionnels', type: 'produit'),
        Account(id: '772', number: '772', name: '(Compte à la disposition des entités pour enregistrer, en cours d\'exercice, les produits sur exercices antérieurs)', type: 'produit'),

        Account(id: '778', number: '778', name: 'Autres produits exceptionnels', type: 'produit'),

        Account(id: '78', number: '78', name: 'Reprises sur amortissements, dépréciations et provisions', type: 'produit'),
        Account(id: '781', number: '781', name: 'Reprises sur amortissements, dépréciations et provisions (à inscrire dans les produits d\'exploitation)', type: 'produit'),
        Account(id: '7811', number: '7811', name: 'Reprises sur amortissements des immobilisations incorporelles et corporelles', type: 'produit'),
        Account(id: '78111', number: '78111', name: 'Immobilisations incorporelles', type: 'produit'),
        Account(id: '78112', number: '78112', name: 'Immobilisations corporelles', type: 'produit'),
        Account(id: '7815', number: '7815', name: 'Reprises sur provisions d\'exploitation', type: 'produit'),
        Account(id: '7816', number: '7816', name: 'Reprises sur dépréciations des immobilisations incorporelles et corporelles', type: 'produit'),
        Account(id: '78161', number: '78161', name: 'Immobilisations incorporelles', type: 'produit'),
        Account(id: '78162', number: '78162', name: 'Immobilisations corporelles', type: 'produit'),
        Account(id: '7817', number: '7817', name: 'Reprises sur dépréciations des actifs circulants', type: 'produit'),
        Account(id: '78173', number: '78173', name: 'Stocks et en-cours', type: 'produit'),
        Account(id: '78174', number: '78174', name: 'Créances', type: 'produit'),

        Account(id: '786', number: '786', name: 'Reprises sur dépréciations et provisions (à inscrire dans les produits financiers)', type: 'produit'),
        Account(id: '7865', number: '7865', name: 'Reprises sur provisions financières', type: 'produit'),
        Account(id: '7866', number: '7866', name: 'Reprises sur dépréciations des éléments financiers', type: 'produit'),
        Account(id: '78662', number: '78662', name: 'Immobilisations financières', type: 'produit'),
        Account(id: '78665', number: '78665', name: 'Valeurs mobilières de placement', type: 'produit'),

        Account(id: '787', number: '787', name: 'Reprises sur dépréciations et provisions (à inscrire dans les produits exceptionnels)', type: 'produit'),
        Account(id: '7872', number: '7872', name: 'Reprises sur provisions réglementées (immobilisations)', type: 'produit'),
        Account(id: '78725', number: '78725', name: 'Amortissements dérogatoires', type: 'produit'),
        Account(id: '7873', number: '7873', name: 'Reprises sur provisions réglementées (stocks)', type: 'produit'),
        Account(id: '7874', number: '7874', name: 'Reprises sur autres provisions réglementées', type: 'produit'),
        Account(id: '7875', number: '7875', name: 'Reprises sur provisions exceptionnelles', type: 'produit'),
        Account(id: '7876', number: '7876', name: 'Reprises sur dépréciations exceptionnelles', type: 'produit'),

      ];

  static List<Account> get allAccounts => defaultAccounts;

  static List<Account> get charges =>
      allAccounts.where((a) => a.type == 'charge').toList();

  static List<Account> get produits =>
      allAccounts.where((a) => a.type == 'produit').toList();
}