// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQce8EJqKssqD182Xb426X3hzi_eK6DpE',
    appId: '1:983402703828:web:df5635cebf98e1cc200441',
    messagingSenderId: '983402703828',
    projectId: 'alt-app-8ccfc',
    authDomain: 'alt-app-8ccfc.firebaseapp.com',
    storageBucket: 'alt-app-8ccfc.firebasestorage.app',
    measurementId: 'G-9BPMEVT15B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUZUf37v2AIdBLj0xANByeYB-tSdtX1w',
    appId: '1:983402703828:android:348f6db74dc02831200441',
    messagingSenderId: '983402703828',
    projectId: 'alt-app-8ccfc',
    storageBucket: 'alt-app-8ccfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1c9wwQxlVCNeUNyBbKlhHqsKgk7jzFk',
    appId: '1:983402703828:ios:ebdb5f10d3c667ee200441',
    messagingSenderId: '983402703828',
    projectId: 'alt-app-8ccfc',
    storageBucket: 'alt-app-8ccfc.firebasestorage.app',
    iosBundleId: 'altassistante.fr.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1c9wwQxlVCNeUNyBbKlhHqsKgk7jzFk',
    appId: '1:983402703828:ios:ebdb5f10d3c667ee200441',
    messagingSenderId: '983402703828',
    projectId: 'alt-app-8ccfc',
    storageBucket: 'alt-app-8ccfc.firebasestorage.app',
    iosBundleId: 'altassistante.fr.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQce8EJqKssqD182Xb426X3hzi_eK6DpE',
    appId: '1:983402703828:web:9ba0105ceb432177200441',
    messagingSenderId: '983402703828',
    projectId: 'alt-app-8ccfc',
    authDomain: 'alt-app-8ccfc.firebaseapp.com',
    storageBucket: 'alt-app-8ccfc.firebasestorage.app',
    measurementId: 'G-C0SEVKVX59',
  );
}
