platform :ios, '16.0'

# On pointe vers votre dossier Flutter
load '/Users/altynai/flutter/packages/flutter_tools/bin/podhelper.rb'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # --- CORRECTION : Les pods doivent être ICI ---
  # On ajoute uniquement les langues officiellement supportées par ML Kit Text Recognition v2
  pod 'GoogleMLKit/TextRecognition', '~> 9.0.0'          # Latin (Français, Anglais, Allemand, Italien, etc.)
  pod 'GoogleMLKit/TextRecognitionChinese', '~> 9.0.0'
  pod 'GoogleMLKit/TextRecognitionDevanagari', '~> 9.0.0'
  pod 'GoogleMLKit/TextRecognitionJapanese', '~> 9.0.0'
  pod 'GoogleMLKit/TextRecognitionKorean', '~> 9.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Correction pour les architectures et la version cible
      config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"

      # Assure que toutes les cibles utilisent au moins la version 16.0
      if Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']) < Gem::Version.new('16.0')
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end