# Fichier de configuration corrigé avec votre chemin SDK
platform :ios, '13.0'

# On pointe directement vers votre dossier Flutter trouvé par le doctor
load '/Users/altynai/flutter/packages/flutter_tools/bin/podhelper.rb'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
